### ISSUE TITLE
Missing features in the readme

### ISSUE THREAD

**Issue by Wiebsonice** [kriskuiper/functional-programming#26]
Good start on your `readme`, clear and well written. Altough some key features are missing. Please check out the checklist.

- [x] Try to include a description of the project to help people understand what it is that you're builing here.
- [x] Missing list of added features, such as data cleaning, Rollup.js bundeler, etc etc
- [x] Concept and image of concept, you've made a brief start on this in your wiki, either write a short summary in your `readme` and include a screenshot, and link to your wiki page about your concept.
- [x] It'd be a good idea to give a short introduction to the data you've used.
- [x] Last but not least, (im not sure if you want to give acknowledgements, because you've probably didnt have a lot of help, you're mostly giving help) but if you had include them :)

**Comment by kriskuiper** [comment]
@Wiebsonice shameless plug with the last point lol 🎉
